export const sentences = [
  {
    true: "Die Flagge war eine deutsche Flagge.",
    false: "Die Flagge war eine französische Flagge.",
  },
  {
    true: "Die Glühbirne war aus.",
    false: "Die Glühbirne war zerbrochen.",
  },
  {
    true: "Die Tasche war schwarz.",
    false: "Die Tasche war grau.",
  },
  {
    true: "Die Kokosnuss war in Stücke geschnitten.",
    false: "Die Kokosnuss war ganz.",
  },
  {
    true: "Das Notizbuch hatte eine Ringbindung.",
    false: "Das Notizbuch hatte Trennblätter.",
  },
  {
    true: "Das Sushi bestand aus Fisch.",
    false: "Das Sushi war aus Gemüse.",
  },
  {
    true: "Der Saft wurde aus Orangen gepresst.",
    false: "Der Saft wurde aus Pfirsichen gepresst.",
  },
  {
    true: "Der Ring war aus Gold.",
    false: "Der Ring war aus Silber.",
  },
  {
    true: "Der Schal hatte Streifen.",
    false: "Der Schal war beige.",
  },
  {
    true: "Das Bett war ein Doppelbett.",
    false: "Das Bett war ein Einzelbett.",
  },
  {
    true: "Der Gürtel war aus Leder.",
    false: "Der Gürtel war aus Stoff.",
  },
  {
    true: "Der Eimer hatte Punkte.",
    false: "Der Eimer hatte Karos.",
  },
  {
    true: "Die Blume war eine Rose.",
    false: "Die Blume war eine Margerite.",
  },
  {
    true: "Die Flöte war aus Holz.",
    false: "Die Flöte war aus Plastik.",
  },
  {
    true: "Der Keks enthielt Schokolade.",
    false: "Der Keks hatte eine Sahnefüllung.",
  },
  {
    true: "Die Brille war eine Sehhilfe.",
    false: "Die Brille war eine Sonnenbrille.",
  },
  {
    true: "Der Hotdog war in einem langen Brötchen.",
    false: "Der Hotdog hatte Ketchup.",
  },
  {
    true: "Der Koffer hatte Räder.",
    false: "Der Koffer hatte Aufkleber.",
  },
  {
    true: "Die Münze war eine 5-Cent-Münze.",
    false: "Die Münze war eine 2-Cent-Münze.",
  },
  {
    true: "Das Brot war geschnitten.",
    false: "Das Brot war rund.",
  },
  {
    true: "Die Paprika war gelb.",
    false: "Die Paprika war grün.",
  },
  {
    true: "Der Käse hatte Löcher.",
    false: "Der Käse war Streichkäse.",
  },
  {
    true: "Die Kerze war rot.",
    false: "Die Kerze war lila.",
  },
  {
    true: "Das Glas war ein Rotweinglas.",
    false: "Das Glas war ein Weißweinglas.",
  },
  {
    true: "Das Handy hatte installierte Apps.",
    false: "Das Handy hatte eine Katzen als Hintergrundbild.",
  },
  {
    true: "Der Hoodie hatte eine Kapuze.",
    false: "Der Hoodie hatte Knöpfe.",
  },
  {
    true: "Die Stiefel hatten Schnürsenkel.",
    false: "Die Stiefel hatten Klettverschlüsse.",
  },
  {
    true: "Das Skateboard hatte Räder.",
    false: "Das Skateboard war elektrisch.",
  },
  {
    true: "Die Tüte war aus Papier.",
    false: "Die Tüte war aus Plastik.",
  },
  {
    true: "Die Kopfhörer hatten Kabel.",
    false: "Die Kopfhörer waren kabellos.",
  },
  {
    true: "Die Geige war in einem Etui.",
    false: "Die Geige war zerbrochen.",
  },
  {
    true: "Der Hut war braun.",
    false: "Der Hut war aus Stroh.",
  },
  {
    true: "Der Schläger war ein Tennisschläger.",
    false: "Der Schläger war ein Tischtennisschläger.",
  },
  {
    true: "Die Pizza war mit Tomaten belegt.",
    false: "Die Pizza war mit Salami belegt.",
  },
  {
    true: "Der Ball war ein Basketball.",
    false: "Der Ball war ein Fußball.",
  },
  {
    true: "Die Kartoffel war mit Schale.",
    false: "Die Kartoffel war geschält.",
  },
  {
    true: "Der Schlauch war aufgerollt.",
    false: "Der Schlauch war angeschlossen.",
  },
  {
    true: "Das Sandwich war quadratisch.",
    false: "Das Sandwich war dreieckig.",
  },
  {
    true: "Die Sandalen hatten Blumenmuster.",
    false: "Die Sandalen hatten Automuster.",
  },
  {
    true: "Die Karotte war orange.",
    false: "Die Karotte war geraspelt.",
  },
  {
    true: "Der Rock war weiß.",
    false: "Der Rock hatte Pailletten",
  },
  {
    true: "Der Helm war ein Fahrradhelm.",
    false: "Der Helm war ein Bauhelm.",
  },
  {
    true: "Der Lautsprecher stand aufrecht.",
    false: "Der Lautsprecher lag flach.",
  },
  {
    true: "Die Zigarette war unversehrt.",
    false: "Die Zigarette war nass.",
  },
  {
    true: "Die Waage zeigte 0 an.",
    false: "Die Waage zeigte 100 an.",
  },
  {
    true: "In der Badewanne lag ein Handtuch.",
    false: "In der Badewanne stand eine Shampooflasche.",
  },
  {
    true: "Der Faden war blau.",
    false: "Der Faden war weinrot.",
  },
  {
    true: "Die Seife war ein Stück Seife.",
    false: "Die Seife war flüssig.",
  },
];

export const trueObjectsName = [
  "Flagge",
  "Glühbirne",
  "Tasche",
  "Kokosnuss",
  "Notizbuch",
  "Sushi",
  "Saft",
  "Ring",
  "Schal",
  "Bett",
  "Gürtel",
  "Eimer",
  "Blume",
  "Flöte",
  "Keks",
  "Brille",
  "Hotdog",
  "Koffer",
  "Münze",
  "Brot",
  "Paprika",
  "Käse",
  "Kerze",
  "Glas",
  "Handy",
  "Hoodie",
  "Stiefel",
  "Skateboard",
  "Tüte",
  "Kopfhörer",
  "Geige",
  "Hut",
  "Schläger",
  "Pizza",
  "Ball",
  "Kartoffel",
  "Schlauch",
  "Sandwich",
  "Sandalen",
  "Karotte",
  "Rock",
  "Helm",
  "Lautsprecher",
  "Zigarette",
  "Waage",
  "Badewanne",
  "Faden",
  "Seife",
];

export const falseObjectsName = [
  "Nüsse",
  "Handtuchhalter",
  "Fass",
  "Avocado",
  "Schachbrett",
  "Computermaus",
  "Schallplatte",
  "Buch",
  "Salat",
  "teclado",
  "Chipstüte",
  "Sparbüchse",
  "Stecker",
  "Sardinen",
  "Spielkarten",
  "Pfanne",
  "Weihrauch",
  "Bonbons",
  "Projektor",
  "Kleiderständer",
  "Tablet",
  "Tonkrug",
  "Bleistift",
  "Knopf",
  "Postkarte",
  "Haftnotiz",
  "CD-Hülle",
  "Gewürzbox",
  "Geschenk",
  "Chinesische Laterne",
  "Schmuckkasten",
  "Trophäe",
  "Flaschenkorken",
  "Schüssel",
  "Ständer",
  "Kaffee",
  "Wischmopp",
  "Aschenbecher",
  "Hocker",
  "Essstäbchen",
  "Puzzle",
  "Fahrradhandschuhe",
  "Aktenordner",
  "Haustürklingel",
  "Fenster",
  "Halskette",
  "Ladegerät",
  "Tulpe",
];
