export const trueSentences = [
  "La bandera era una bandera de Alemania.",
  "La bombilla estaba apagada.",
  "El bolso era negro.",
  "El coco esaba partido en trozos.",
  "La libreta tenía anillas.",
  "El sushi era de pescado.",
  "El zumo era de naranja.",
  "El anillo era de oro.",
  "La bufanda era de rallas.",
  "La cama era una cama de matrimonio.",
  "El cinturón era de cuero.",
  "El cubo tenía lunares.",
  "La flor era una rosa.",
  "La flauta era de madera.",
  "La galleta tenía chocolate.",
  "Las gafas eran gafas de ver.",
  "El perrito caliente tenía un pan alargado.",
  "La maleta tenía ruedas.",
  "La moneda era una moneda de 5 céntimos.",
  "El pan estaba cortado.",
  "El pimiento era amarillo.",
  "El queso tenía agujeros.",
  "La vela era roja.",
  "La copa era una copa de vino tinto.",
  "El móvil tenía aplicaciones instaladas.",
  "La sudadera tenía capucha.",
  "Las botas tenían cordones.",
  "El monopatín tenía ruedas.",
  "La bolsa era de papel.",
  "Los auriculares tenían cables.",
  "El violín estaba en una funda.",
  "El sombrero era marrón.",
  "La raqueta era una raqueta de tenis.",
  "La pizza tenía tomate.",
  "La pelota era una pelota de baloncesto.",
  "La patata tenía piel.",
  "La manguera estaba enrollada.",
  "El sandwich tenía forma cuadrada.",
  "Las chanclas tenían dibujos de flores.",
  "La zanahoria era naranja.",
  "La falda era blanca.",
  "El casco era un casco de bicicleta.",
  "El altavoz estaba de pie.",
  "El cigarro estaba intacto.",
  "El peso marcaba 0.",
  "En la bañera había una toalla.",
  "El hilo era de color azul.",
  "El jabón era jabón en pastilla.",
];

export const falseSentences = [
  "La bandera era una bandera de Francia.",
  "La bombilla tenía el cristal roto.",
  "El bolso era gris.",
  "El coco estaba entero.",
  "La libreta tenía separadores.",
  "El sushi era de verdura.",
  "El zumo era de melocotón.",
  "El anillo era de plata.",
  "La bufanda era beige.",
  "La cama era una cama individual.",
  "El cinturón era de tela.",
  "El cubo tenía cuadros.",
  "La flor era una margarita.",
  "La flauta era de plástico.",
  "La galleta tenía crema.",
  "Las gafas eran gafas de sol.",
  "El perrito caliente tenía ketchup.",
  "La maleta tenía pegatinas.",
  "La moneda era una moneda de 2 céntimos.",
  "El pan era redondo.",
  "El pimiento era verde.",
  "El queso era un queso de untar.",
  "La vela era morada.",
  "La copa era una copa de vino blanco.",
  "El móvil tenía un fondo de pantalla de un gato.",
  "La sudadera tenía botones.",
  "Las botas tenían velcro.",
  "El monopatín era eléctrico.",
  "La bolsa era de plástico.",
  "Los auriculares eran inalámbricos.",
  "El violín estaba partido por la mitad.",
  "El sombrero era de paja.",
  "La raqueta era una raqueta de pádel.",
  "La pizza tenía carne.",
  "La pelota era una pelota de fútbol.",
  "La patata estaba pelada.",
  "La manguera estaba enchufada.",
  "El sandwich tenía forma de triángulo.",
  "Las chanclas tenáin dibujos de coches.",
  "La zanahoria estaba rallada.",
  "La falda tenía lentejuelas.",
  "El casco era un casco de obra.",
  "El altavoz estaba tumbado.",
  "El cigarro estaba mojado.",
  "El peso marcaba 100.",
  "En la bañera había un bote de champú.",
  "El hilo era de color burdeos.",
  "El jabón era jabón líquido.",
];

export const trueObjectsName = [
  "bandera",
  "bombilla",
  "bolso",
  "coco",
  "libreta",
  "sushi",
  "zumo",
  "anillo",
  "bufanda",
  "cama",
  "cinturón",
  "cubo",
  "flor",
  "flauta",
  "galleta",
  "gafas",
  "perrito caliente",
  "maleta",
  "moneda",
  "pan",
  "pimiento",
  "queso",
  "vela",
  "copa",
  "móvil",
  "sudadera",
  "botas",
  "monopatín",
  "bolsa",
  "auriculares",
  "violín",
  "sombrero",
  "raqueta",
  "pizza",
  "pelota",
  "patata",
  "manguera",
  "sandwich",
  "chanclas",
  "zanahoria",
  "falda",
  "casco",
  "altavoz",
  "cigarro",
  "peso",
  "bañera",
  "hilo",
  "jabón",
];


export const falseObjectsName = [
  "patata1",
  "patata2",
  "patata3",
  "patata4",
  "patata5",
];